name: healing_guide_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  equatable: ^2.0.5
  faker: ^2.2.0
  logger: ^2.4.0
  go_router: ^14.3.0
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  intl: any
  extended_masked_text: ^3.0.1
  flutter_native_splash: ^2.4.2
  http: ^1.2.2
  cronet_http: ^1.3.2
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  get_it: ^8.0.2
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router_builder: any
  build_runner: any
  build_verify: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/med_specialties/

  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700