name: healing_guide_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  hydrated_bloc: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: almarai
      fonts:
        - asset: fonts/Almarai-Regular.tff
        - asset: fonts/Almarai-Bold.tff
          weight: 700